===========================================
"// --- 4. ADMIN ROUTES (Protected by SuperID) ---\n// bcrypt is already required at the top\n\napp.get('/admin/admission-applications', (req, res) => {"

===========================================
"// Feature 3: Admitted Students List\napp.get('/admin/admission-applications/admitted-list', (req, res) => {\n    const tokenadmin = req.cookies.jwt;\n    if (!tokenadmin) return res.redirect('/loginpanel');\n\n    try {\n        const decode = jwt.verify(tokenadmin, \"secretkeysvpcet\");\n        if (decode.role !== 'SuperID') {\n            req.flash('message', 'Unauthorised Access');\n            return res.redirect('/loginpanel');\n        }\n\n        dbbconnection.getConnection((err, connection) => {\n            if (err) {\n                req.flash('message', 'Database error');\n                return res.redirect('back');\n            }\n            const query = \"SELECT * FROM hostel_admission_applications WHERE status = 'Admitted' ORDER BY allotted_block ASC, allotted_room ASC, allotted_bed ASC\";\n            \n            connection.query(query, (err, result) => {\n                connection.release();\n                if (err) {\n                    req.flash('message', 'Error fetching admitted students');\n                    return res.redirect('back');\n                }\n\n                const grouped = {};\n                result.forEach(row => {\n                    const block = row.allotted_block || 'Unassigned';\n                    if (!grouped[block]) grouped[block] = [];\n                    grouped[block].push(row);\n                });\n                \n                const blockKeys = Object.keys(grouped).sort();\n\n                res.render('admin_admitted_list', {\n                    grouped,\n                    blockKeys,\n                    total: result.length,\n                    message: req.flash('message')\n                });\n            });\n        });\n\n    } catch (e) {\n        res.clearCookie(\"jwt\");\n        return res.redirect('/loginpanel');\n    }\n});\n\napp.get('/admin/admission-applications/:id', (req, res) => {"

===========================================
"// Feature 1: Export to Excel for hostel_admission_applications (via Python openpyxl)\napp.get('/admin/admission-applications/export', (req, res) => {\n    const tokenadmin = req.cookies.jwt;\n    if (!tokenadmin) return res.redirect('/loginpanel');\n\n    try {\n        const decode = jwt.verify(tokenadmin, \"secretkeysvpcet\");\n        if (decode.role !== 'SuperID') {\n            req.flash('message', 'Unauthorised Access');\n            return res.redirect('/loginpanel');\n        }\n\n        const filter = (req.query.filter || 'all').toLowerCase();\n        const validFilters = ['all', 'pending', 'admitted', 'rejected'];\n        const safeFilter = validFilters.includes(filter) ? filter : 'all';\n\n        let query = \"SELECT * FROM hostel_admission_applications\";\n        if (safeFilter === 'pending') {\n            query += \" WHERE status = 'Pending'\";\n        } else if (safeFilter === 'admitted') {\n            query += \" WHERE status = 'Admitted'\";\n        } else if (safeFilter === 'rejected') {\n            query += \" WHERE status = 'Rejected'\";\n        }\n        query += \" ORDER BY created_at DESC\";\n\n        dbbconnection.getConnection((err, connection) => {\n            if (err) {\n                req.flash('message', 'Database error');\n                return res.redirect('back');\n            }\n            connection.query(query, [], (err, results) => {\n                connection.release();\n                if (err) {\n                    req.flash('message', 'Error fetching applications for export');\n                    return res.redirect('back');\n                }\n\n                const titleLabel = safeFilter.charAt(0).toUpperCase() + safeFilter.slice(1);\n                const title = 'Hostel Admissions   -   ' + titleLabel + ' List';\n\n                const payload = {\n                    title: title,\n                    rows: results.map(row => ({\n                        allotted_room: row.allotted_room || '',\n                        allotted_bed: row.allotted_be
<truncated 2288 bytes>

===========================================
"// Edit admission application details (SuperID only)\napp.get('/admin/admission-applications/:id/edit', (req, res) => {\n    const tokenadmin = req.cookies.jwt;\n    if (!tokenadmin) return res.redirect('/loginpanel');\n\n    try {\n        const decode = jwt.verify(tokenadmin, \"secretkeysvpcet\");\n        if (decode.role !== 'SuperID') {\n            req.flash('message', 'Unauthorised Access');\n            return res.redirect('/loginpanel');\n        }\n\n        dbbconnection.getConnection((err, connection) => {\n            if (err) {\n                req.flash('message', 'Database error');\n                return res.redirect('back');\n            }\n            connection.query(\"SELECT * FROM hostel_admission_applications WHERE id = ?\", [req.params.id], (err, result) => {\n                connection.release();\n                if (err || result.length === 0) {\n                    req.flash('message', 'Application not found');\n                    return res.redirect('/admin/admission-applications');\n                }\n                res.render('admin_admission_edit', {\n                    app: result[0],\n                    message: req.flash('message'),\n                    role: decode.role\n                });\n            });\n        });\n    } catch (e) {\n        res.clearCookie(\"jwt\");\n        return res.redirect('/loginpanel');\n    }\n});\n\napp.post('/admin/admission-applications/:id/edit', (req, res) => {\n    const tokenadmin = req.cookies.jwt;\n    if (!tokenadmin) return res.redirect('/loginpanel');\n\n    try {\n        const decode = jwt.verify(tokenadmin, \"secretkeysvpcet\");\n        if (decode.role !== 'SuperID') {\n            req.flash('message', 'Unauthorised Access');\n            return res.redirect('/loginpanel');\n        }\n\n        const appId = req.params.id;\n        const {\n            full_name, father_name, father_occupation, mother_name, mother_occupation,\n            permanent_address, parent_phone, student_mobile, admission_year, branch,\n            dob
<truncated 1671 bytes>

